/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import dao.DaoProducto;
import javax.swing.JOptionPane;
import modelos.Producto;

/**
 *
 * @author Nelson
 */
public class CrearProductos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearProductos
     */
    public CrearProductos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCaberceraCrearPro = new javax.swing.JPanel();
        lblCrearPro = new javax.swing.JLabel();
        panelCuerpoCrearPro = new javax.swing.JPanel();
        lblNombreProdcuto = new javax.swing.JLabel();
        txtCajaCrearPro = new javax.swing.JTextField();
        lblRefePro = new javax.swing.JLabel();
        txtCajarReferenciaPro = new javax.swing.JTextField();
        lblTemperaturaPro = new javax.swing.JLabel();
        txtCajaTemperaturaPro = new javax.swing.JTextField();
        lblValorBasePro = new javax.swing.JLabel();
        txtCajaValorBasePro = new javax.swing.JTextField();
        panelBotonesCrearPro = new javax.swing.JPanel();
        btnCrearProducto = new javax.swing.JButton();
        btnCancelarPro = new javax.swing.JButton();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(692, 479));

        panelCaberceraCrearPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCrearPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCrearPro.setText("CREAR PRODUCTO");

        javax.swing.GroupLayout panelCaberceraCrearProLayout = new javax.swing.GroupLayout(panelCaberceraCrearPro);
        panelCaberceraCrearPro.setLayout(panelCaberceraCrearProLayout);
        panelCaberceraCrearProLayout.setHorizontalGroup(
            panelCaberceraCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaberceraCrearProLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(lblCrearPro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCaberceraCrearProLayout.setVerticalGroup(
            panelCaberceraCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaberceraCrearProLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblCrearPro)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelCuerpoCrearPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombreProdcuto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombreProdcuto.setText("NOMBRE:");

        txtCajaCrearPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCajaCrearProActionPerformed(evt);
            }
        });

        lblRefePro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRefePro.setText("REFERENCIA:");

        lblTemperaturaPro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTemperaturaPro.setText("TEMPERATURA:");

        lblValorBasePro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorBasePro.setText("VALOR BASE:");

        javax.swing.GroupLayout panelCuerpoCrearProLayout = new javax.swing.GroupLayout(panelCuerpoCrearPro);
        panelCuerpoCrearPro.setLayout(panelCuerpoCrearProLayout);
        panelCuerpoCrearProLayout.setHorizontalGroup(
            panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearProLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuerpoCrearProLayout.createSequentialGroup()
                            .addComponent(lblValorBasePro)
                            .addGap(79, 79, 79))
                        .addGroup(panelCuerpoCrearProLayout.createSequentialGroup()
                            .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombreProdcuto)
                                .addComponent(lblRefePro))
                            .addGap(63, 63, 63)))
                    .addGroup(panelCuerpoCrearProLayout.createSequentialGroup()
                        .addComponent(lblTemperaturaPro)
                        .addGap(63, 63, 63)))
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCajarReferenciaPro, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCajaCrearPro)
                        .addComponent(txtCajaTemperaturaPro, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                        .addComponent(txtCajaValorBasePro)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        panelCuerpoCrearProLayout.setVerticalGroup(
            panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearProLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProdcuto)
                    .addComponent(txtCajaCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRefePro)
                    .addComponent(txtCajaValorBasePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperaturaPro)
                    .addComponent(txtCajarReferenciaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValorBasePro)
                    .addComponent(txtCajaTemperaturaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        panelBotonesCrearPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrearProducto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearProducto.setText("CREAR");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        btnCancelarPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelarPro.setText("CANCELAR");
        btnCancelarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesCrearProLayout = new javax.swing.GroupLayout(panelBotonesCrearPro);
        panelBotonesCrearPro.setLayout(panelBotonesCrearProLayout);
        panelBotonesCrearProLayout.setHorizontalGroup(
            panelBotonesCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesCrearProLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnCrearProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarPro)
                .addGap(95, 95, 95))
        );
        panelBotonesCrearProLayout.setVerticalGroup(
            panelBotonesCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesCrearProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotonesCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearProducto)
                    .addComponent(btnCancelarPro))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCaberceraCrearPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCuerpoCrearPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotonesCrearPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(panelCaberceraCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCuerpoCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBotonesCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtCajaCrearPro.setText("");
        txtCajarReferenciaPro.setText("");
        txtCajaTemperaturaPro.setText("");
        txtCajaValorBasePro.setText("");
        txtCajaCrearPro.requestFocus();
    }
    
    private void txtCajaCrearProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCajaCrearProActionPerformed

    }//GEN-LAST:event_txtCajaCrearProActionPerformed

    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        //******************************************
        //definicion de variables
        //******************************************
        String cajaNombre, cajaReferencia;
        Double cajaTemperatura, cajaValorBase;
        DaoProducto objDaoProducto;
        Producto objProducto;
        //******************************************
        //******************************************
        //capturar la informacion
        //******************************************
        cajaNombre = txtCajaCrearPro.getText();
        cajaReferencia = txtCajarReferenciaPro.getText();
        cajaTemperatura = Double.parseDouble(txtCajaTemperaturaPro.getText());
        cajaValorBase = Double.parseDouble(txtCajaValorBasePro.getText());
        //******************************************

        if (cajaNombre.isEmpty() || cajaReferencia.isEmpty() || cajaTemperatura == null || cajaValorBase == null) {
            JOptionPane.showMessageDialog(panelCuerpoCrearPro, "Los valores son obligatorios.");
        } else {
            //******************************************
            //creacion de objetos
            //******************************************
            objDaoProducto = new DaoProducto();
            objProducto = new Producto();
            //******************************************
            objProducto.setNombre(cajaNombre);
            objProducto.setId(cajaReferencia);
            objProducto.setTemperatura(cajaTemperatura);
            objProducto.setValorBase(cajaValorBase);
            
            if (objDaoProducto.agregar(objProducto)){
                JOptionPane.showMessageDialog(panelCuerpoCrearPro, "Registro agregado correctamente");
            }else{
                JOptionPane.showMessageDialog(panelCuerpoCrearPro, "ERROR!!!!!!!!!!");
            }
            limpiarCajas();
        }
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void btnCancelarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarProActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPro;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JLabel lblCrearPro;
    private javax.swing.JLabel lblNombreProdcuto;
    private javax.swing.JLabel lblRefePro;
    private javax.swing.JLabel lblTemperaturaPro;
    private javax.swing.JLabel lblValorBasePro;
    private javax.swing.JPanel panelBotonesCrearPro;
    private javax.swing.JPanel panelCaberceraCrearPro;
    private javax.swing.JPanel panelCuerpoCrearPro;
    private javax.swing.JTextField txtCajaCrearPro;
    private javax.swing.JTextField txtCajaTemperaturaPro;
    private javax.swing.JTextField txtCajaValorBasePro;
    private javax.swing.JTextField txtCajarReferenciaPro;
    // End of variables declaration//GEN-END:variables
}
